name: CI Build by Sunil

on:
  push:
    branches: main
  
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: Checkout
    uses: actions/checkout@v4

    steps: run a script
    run: echo "Hello, World!"